// export { default as Navbar } from './Navbar/Navbar'
// export { default as Footer } from './Footer/Footer'
// export { default as Clouds } from './Clouds/Clouds'
export { default as Witch } from './Witch/Witch'
export { default as ThunderStorm } from './ThunderStorm/ThunderStorm'
