export { default as Home } from './Home/Home'
export { default as MainPage } from './MainPage/MainPage'
export { default as FemaleSerialKillers } from './FemaleSerialKillers/FemaleSerialKillers'
export { default as MaleSerialKillers } from './MaleSerialKillers/MaleSerialKillers'
export { default as Types } from './Types/Types'
export { default as Psychology } from './Psychology/Psychology'